name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-demo-app:latest

      # Step 4: Pull and run the Docker image on the runner
      - name: Pull and run Docker image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-demo-app:latest
          docker stop nodejs-app || true
          docker rm nodejs-app || true
          docker run -d --name nodejs-app -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-demo-app:latest
